language: c
env:
  global:
    - ARDUINO_IDE_VERSION="1.8.5"
    - ARDUINO_ESP32_VERSION="1.0.1"
    - LIBRARY_NAME="SIM808"
  matrix:
    - BOARD="arduino:avr:uno"
    - BOARD="esp32:esp3:pico32"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
  - sudo mv arduino-$ARDUINO_IDE_VERSION /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - arduino --pref boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json --save-prefs
  - arduino --install-boards esp32:esp32:$ARDUINO_ESP32_VERSION
install:
 - ln -s $PWD /usr/local/share/arduino/libraries/$LIBRARY_NAME
 - arduino --install-library "ArduinoLog"
script:
 - arduino --verify --board $BOARD $PWD/examples/AcquireGPSPosition/AcquireGPSPosition.ino
 - arduino --verify --board $BOARD $PWD/examples/GeneralInformation/GeneralInformation.ino
 - arduino --verify --board $BOARD $PWD/examples/HttpPost/HttpPost.ino
 - arduino --verify --board $BOARD $PWD/examples/Tester/Tester.ino
notifications:
  email:
    on_success: change
    on_failure: change